name: Hello World Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World!"

      - name: Show current date
        run: date

      - name: List current directory contents
        run: ls -l